import json
import sys
from pathlib import Path

import feedparser


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from pipeline import PipelineResult, run_pipeline
from sqlite_ops import get_conn


SCHEMA_SQL = ROOT / "db" / "schema.sql"
FIXTURE_RSS = ROOT / "tests" / "fixtures" / "sample_rss.xml"
ORIGINAL_PARSE = feedparser.parse
CONFIG_DIR = ROOT / "config"


def init_temp_db(tmp_path: Path) -> Path:
    db_path = tmp_path / "neican.sqlite"
    with get_conn(db_path) as conn:
        conn.executescript(SCHEMA_SQL.read_text(encoding="utf-8"))
    return db_path


def write_sources(tmp_path: Path) -> Path:
    sources_path = tmp_path / "sources.yaml"
    sources_path.write_text(
        """
sources:
  - name: "Fixture Feed"
    type: rss
    url: "https://example.com/feed.xml"
    enabled: true
    trust_level: 6
    language: en
    fetch_interval_minutes: 120
""".lstrip(),
        encoding="utf-8",
    )
    return sources_path


def fake_parse(_url):
    return ORIGINAL_PARSE(FIXTURE_RSS.read_text(encoding="utf-8"))


def test_run_pipeline_mock_end_to_end(tmp_path, monkeypatch):
    db_path = init_temp_db(tmp_path)
    sources_path = write_sources(tmp_path)
    site_dir = tmp_path / "hugo-site"
    memory_dir = tmp_path / "memory-wiki"
    monkeypatch.setattr("fetch_sources.feedparser.parse", fake_parse)

    result = run_pipeline(
        db_path=db_path, site_dir=site_dir, memory_dir=memory_dir,
        sources_path=sources_path, config_dir=CONFIG_DIR,
        date="2026-05-01", limit=2, mock=True,
    )

    assert isinstance(result, PipelineResult)
    assert result.fetch["inserted_count"] == 2
    assert result.extract["processed_count"] == 2
    assert result.model["modeled_count"] == 2
    assert result.decide["decided_count"] == 2

    # Daily brief is now generated by dedicated product, not legacy export_hugo
    assert result.export == {"daily_briefs": 0, "insights": 0, "skipped_approved": 0, "failed_count": 0}
    assert result.daily_brief["exported"] is True or result.daily_brief["events_count"] >= 0

    # Entity/topic registries were synced
    assert result.entity_registry["synced"] >= 1
    assert result.topic_registry["synced"] >= 2

    # All pipeline modules ran without error (content depends on editorial grades)
    assert "generated" in result.timeline
    assert "events_count" in result.daily_brief
    assert "proposed" in result.insight_candidates
    assert "generated" in result.entities
    assert "generated" in result.events
    assert "generated" in result.topic_product


def test_run_pipeline_passes_flags_and_order(monkeypatch, tmp_path):
    calls: list[tuple[str, dict]] = []

    class Result:
        def __init__(self, **kwargs):
            self._data = kwargs

        def to_dict(self):
            return self._data

    def fake_fetch_sources(**kwargs):
        calls.append(("fetch", kwargs))
        return Result(inserted_count=1, skipped_duplicate_count=0, failed_count=0)

    def fake_extract_content(**kwargs):
        calls.append(("extract", kwargs))
        return Result(processed_count=1, failed_count=0)

    def fake_model_events(**kwargs):
        calls.append(("model", kwargs))
        return Result(modeled_count=1, failed_count=0)

    def fake_merge_modeled_events(**kwargs):
        calls.append(("event_store", kwargs))
        return Result(canonical_events=1, merged_events=0, event_sources=1)

    def fake_sync_entity_registry(**kwargs):
        calls.append(("entity_registry", kwargs))
        return Result(synced=1, updated=0, new=1)

    def fake_normalize_events_entities(**kwargs):
        calls.append(("normalize_events", kwargs))
        return 0

    def fake_sync_topic_registry(**kwargs):
        calls.append(("topic_registry", kwargs))
        return Result(synced=1, updated=0, new=1)

    def fake_make_decisions(**kwargs):
        calls.append(("decide", kwargs))
        return Result(decided_count=1, failed_count=0)

    def fake_discover_candidate_tracks(**kwargs):
        calls.append(("candidate_tracks", kwargs))
        return Result(created=1, updated=0, skipped=0)

    def fake_review_candidate_tracks(**kwargs):
        calls.append(("track_review", kwargs))
        return Result(approved=0, merged=1, watch=0, rejected=0)

    def fake_run_timeline_product(**kwargs):
        calls.append(("timeline", kwargs))
        return Result(generated=1, exported_events=1, exported_years=1, exported_tracks=1, skipped=0)

    def fake_run_entity_product(**kwargs):
        calls.append(("entities", kwargs))
        return Result(generated=1, exported=1, source="db")

    def fake_run_event_product(**kwargs):
        calls.append(("events", kwargs))
        return Result(generated=1, exported=1, source="timeline_nodes")

    def fake_run_topic_product(**kwargs):
        calls.append(("topic_product", kwargs))
        return Result(generated=1, exported=1)

    def fake_generate_daily_brief(**kwargs):
        calls.append(("daily_brief", kwargs))
        return Result(date="2026-06-01", events_count=0, tracks_count=0, exported=False)

    def fake_detect_insight_candidates(**kwargs):
        calls.append(("insight_candidates", kwargs))
        return Result(proposed=0, skipped=0)

    def fake_run_insight_product(**kwargs):
        calls.append(("insight_product", kwargs))
        return Result(generated=0, exported=0)

    monkeypatch.setattr("pipeline.fetch_sources", fake_fetch_sources)
    monkeypatch.setattr("pipeline.extract_content", fake_extract_content)
    monkeypatch.setattr("pipeline.model_events", fake_model_events)
    monkeypatch.setattr("pipeline.merge_modeled_events", fake_merge_modeled_events)
    monkeypatch.setattr("pipeline.sync_entity_registry", fake_sync_entity_registry)
    monkeypatch.setattr("pipeline.normalize_events_entities", fake_normalize_events_entities)
    monkeypatch.setattr("pipeline.sync_topic_registry", fake_sync_topic_registry)
    monkeypatch.setattr("pipeline.make_decisions", fake_make_decisions)
    monkeypatch.setattr("pipeline.discover_candidate_tracks", fake_discover_candidate_tracks)
    monkeypatch.setattr("pipeline.review_candidate_tracks", fake_review_candidate_tracks)
    monkeypatch.setattr("pipeline.run_timeline_product", fake_run_timeline_product)
    monkeypatch.setattr("pipeline.run_entity_product", fake_run_entity_product)
    monkeypatch.setattr("pipeline.run_event_product", fake_run_event_product)
    monkeypatch.setattr("pipeline.run_topic_product", fake_run_topic_product)
    monkeypatch.setattr("pipeline.generate_daily_brief", fake_generate_daily_brief)
    monkeypatch.setattr("pipeline.detect_insight_candidates", fake_detect_insight_candidates)
    monkeypatch.setattr("pipeline.run_insight_product", fake_run_insight_product)
    monkeypatch.setattr("pipeline.update_knowledge_assets", lambda **kwargs: Result(entities_created=0, entities_updated=0, topics_created=0, topics_updated=0, timeline_entries=0, claims_written=0))

    result = run_pipeline(
        db_path=tmp_path / "db.sqlite", site_dir=tmp_path / "site",
        memory_dir=tmp_path / "memory", sources_path=tmp_path / "sources.yaml",
        config_dir=tmp_path / "config", date="2026-06-01", limit=5,
        source_name="OpenAI Blog", full_text=True, mock=True, dry_run=False,
    )

    d = result.to_dict()
    assert d["fetch"] == {"inserted_count": 1, "skipped_duplicate_count": 0, "failed_count": 0}
    assert d["event_store"]["canonical_events"] == 1
    assert d["entity_registry"]["synced"] == 1
    assert d["topic_registry"]["synced"] == 1
    assert d["topic_product"]["generated"] == 1
    assert d["daily_brief"]["date"] == "2026-06-01"
    assert d["daily_brief"]["exported"] is False  # no events in mock
    assert d["insight_candidates"]["proposed"] == 0
    assert d["insight_product"]["generated"] == 0
    # Legacy export is now a no-op stub
    assert d["export"] == {"daily_briefs": 0, "insights": 0, "skipped_approved": 0, "failed_count": 0}

    # Verify order: fetch -> extract -> model -> event_store -> entity_registry -> normalize_events -> topic_registry -> decide
    order = [name for name, _ in calls]
    assert order[:8] == ["fetch", "extract", "model", "entity_registry", "normalize_events", "event_store", "topic_registry", "decide"]
    assert calls[0][1]["source_name"] == "OpenAI Blog"
    assert calls[0][1]["full_text"] is True
    assert calls[2][1]["mock"] is True


def test_pipeline_main_json_shape(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(
        "pipeline.run_pipeline",
        lambda **kwargs: PipelineResult(
            date="2026-07-01",
            fetch={"inserted_count": 1, "skipped_duplicate_count": 0, "failed_count": 0},
            extract={"processed_count": 1, "failed_count": 0},
            model={"modeled_count": 1, "failed_count": 0},
            event_store={"canonical_events": 1, "merged_events": 0, "event_sources": 1},
            decide={"decided_count": 1, "failed_count": 0},
            assets={"entities_created": 0, "entities_updated": 0, "topics_created": 0, "topics_updated": 0, "timeline_entries": 0, "claims_written": 0},
            candidate_tracks={"created": 1, "updated": 0, "skipped": 0},
            track_review={"approved": 0, "merged": 1, "watch": 0, "rejected": 0},
            export={"daily_briefs": 0, "insights": 0, "skipped_approved": 0, "failed_count": 0},
            timeline={"generated": 1, "exported_events": 1, "exported_years": 1, "exported_tracks": 1, "skipped": 0},
            entities={"generated": 1, "exported": 1, "source": "db"},
            events={"generated": 1, "exported": 1, "source": "timeline_nodes"},
            entity_registry={"synced": 1, "updated": 0, "new": 1},
            topic_registry={"synced": 1, "updated": 0, "new": 1},
            topic_product={"generated": 1, "exported": 1},
            daily_brief={"date": "2026-07-01", "events_count": 1, "tracks_count": 0, "exported": True},
            insight_candidates={"proposed": 0, "skipped": 0},
            insight_product={"generated": 0, "exported": 0},
        ),
    )

    from pipeline import main
    monkeypatch.setattr(sys, "argv", ["pipeline.py", "--date", "2026-07-01", "--mock"])
    main()
    out = capsys.readouterr().out
    parsed = json.loads(out)
    assert parsed["date"] == "2026-07-01"
    assert parsed["daily_brief"]["exported"] is True
    assert parsed["event_store"]["canonical_events"] == 1
    assert parsed["entity_registry"]["synced"] == 1
    assert parsed["topic_registry"]["synced"] == 1
